name: Check PR fixcloudutils
on:
  push:
    tags:
      - '*.*.*'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  fixcloudutils:
    name: 'fixcloudutils'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Restore dependency cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{hashFiles('**/requirements*.txt')}}
          restore-keys: |
            ${{runner.os}}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      - name: Run tests
        run: tox

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution to PyPI
        if: github.ref_type == 'tag'
        continue-on-error: true # Ignore failure to publish to PyPI (e.g., when re-tagging a release)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_FIXCLOUDUTILS }}
          packages_dir: ./dist/
